name = "Solace"
author = "macuguita"
version = "0.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "55d721e00a6148d24148f25e10a686c0df9a8648e4c29282abd0a92cf0109d83"

[versions]
fabric = "0.19.3"
minecraft = "1.21.1"
unsup = "1.2.7"

[options]
acceptable-game-versions = ["1.21"]
datapack-folder = "datapacks"
