name = "Solace"
author = "macuguita"
version = "0.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "892db746e28668d07037dce97ac174388ba85f3956b6240cbfd5ac3f386df08a"

[versions]
fabric = "0.19.3"
minecraft = "1.21.1"
unsup = "1.2.7"

[options]
acceptable-game-versions = ["1.21"]
datapack-folder = "datapacks"
