name = "Solace"
author = "macuguita"
version = "0.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "87351431fe5d531a1200aa52603056cbe34c59e33cf159fffbb8d3cd668f1f69"

[versions]
fabric = "0.19.3"
minecraft = "1.21.1"
unsup = "1.2.7"

[options]
acceptable-game-versions = ["1.21"]
datapack-folder = "datapacks"
