[flavor_groups.mixed-litter]
name = "Mixed litter"
side = "client"
description = "A mod that adds remodeled versions of Minecraft's vanilla animals."
[[flavor_groups.mixed-litter.choices]]
id = "mixed-litter_accept"
name = "Yes"
description = "Enables remodeled versions of vanilla animals."
[[flavor_groups.mixed-litter.choices]]
id = "mixed-litter_decline"
name = "No"
description = "Disables the remodeled versions of vanilla animals. <b>Please note: this option is unofficial and not supported by the server administrators. If enabling it causes issues, do not request support on the server.</b>"

[metafile.mixed-litter-disable]
flavors="mixed-litter_decline"

[flavor_groups.xaero]
name = "Xaero"
side = "client"
description = "Mods that add a minimap and a world map."
[[flavor_groups.xaero.choices]]
id = "xaero_yes"
name = "Yes"
description = "Enables xaero's mods."
[[flavor_groups.xaero.choices]]
id = "xaero_no"
name = "No"
description = "Does not enable xaero's mods."

[metafile.xaeros-world-map]
flavors="xaero_yes"
[metafile.xaeros-minimap]
flavors="xaero_yes"
[metafile.cobblemon-xaero-config]
flavors="xaero_yes"
[metafile.e19_cobblemon_minimap_icons]
flavors="xaero_yes"

[flavor_groups.emi]
name = "EMI"
side = "client"
description = "EMI recipe viewer."
[[flavor_groups.emi.choices]]
id = "emi_yes"
name = "Yes"
description = "Enables EMI."
[[flavor_groups.emi.choices]]
id = "emi_no"
name = "No"
description = "Does not enable EMI"

[metafile.emi]
flavors="emi_yes"